POST http://localhost:8080/api/data
Content-Type: application/json

{
  "id": "msg-full-simulation-le",
  "value": {
    "payload": "4A00386300004B007D0000004098A21741933B01419400000000409988130000"
  },
  "metadata": {
    "network": {
      "lora": {
        "devEUI": "SIMULATED_DEVICE",
        "port": 3
      }
    }
  }
}